#+TITLE: GRAW - Changelog
#+DESCRIPTION: All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) - though syntax has been adapted to Org-mode syntax,
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html) - well trying actually.

Futhermore, take note that, in general, if a change has no impact on "users", it is leaved out of this file.
For more internal notes, it may be revelant to check the =LOG= files instead (inside =log= repository).

** [Unreleased]

- 2.3.Z: Add distinct participants to a region.
- 2.4.Z: Add participants group / team to a region.
- 2.5.Z: Update data location / backend.

*** [2.2.0] - 2020-12-24

*** Changed

- Drawing process to better actual location rendering.

** 2.2.0 Add multiple participants for one region [YANKED]

GPS traces drawing must be completely reviewed before any other changes.

** [2.1.0] - 2020-12-17

*** Changed

- Distance unit from step to meter.

** [1.3.1] - 2020-12-16

*** Added

- This CHANGELOG to hopefully serve as a good evolution tracker.
