#+TITLE:     GRAW - Inbox
#+SUBTITLE:  Garmin Race Around the World - Inbox
#+AUTHOR:    Midorino
#+EMAIL:     midorino@protonmail.com
#+DESCRIPTION: Ideas, todos, aso
#+LANGUAGE:  en

#+HTML_LINK_HOME: https://midorino.github.io

* :GRAW: Update Garmin challenge
SCHEDULED: <2020-11-30 .+1m>
:PROPERTIES:
:CREATED:  [2020-11-01]
:END:

* :GRAW: Import Garmin data
SCHEDULED: <2020-11-30 .+1w>
:PROPERTIES:
:CREATED:  [2020-11-01]
:END:

* Layers organization

If Leaflet GPX plugin is migrated to vanilla code, layers organization (eg: one for CRAW complete tracks, one for GRAW progress tracks, one for POI?) would be far easier too.

* From Leaflet GPX plugin to vanilla

Consider import only necessary code chunks from Leaflet GPX plugin and (more simply) draw =polylines= from GPX data.
Would ease post work with progress drawing too.

Furthermore, GPX files loading really necessary?
Could consider an export to GeoJSON (balance between upload size and processing speed) or even pure JSON/JS data?

* Relative progress information

In runner information display, add the optimal progress rate in comparison to the actual progress rate (function of data date).

* View for informations

From CHANGELOG, NEWS, VERSION, README files (=*.org=).

* Strava / Garmin API (or alternative)

(Semi)Automatic data crawling (/BeautifulSoup/)?

* WhatsApp API?

Private information (phone number) - not good idea.

Better alternative: News on Garmin challenge + via integrated NEWS feed viewer.

* Google Street View

From current runner progress coordiantes - Open in new tab.

* Move =LOGS.org= to logs/YYYYMMDD.org files

* Waiting animation for Leaflet map loading

- https://github.com/ebrelsford/Leaflet.loading
- https://github.com/makinacorpus/Leaflet.Spin
- http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.50000.html

Logo "Penguins x Pingouins" SVG?

* Moving marker for runners progress

https://github.com/ewoken/Leaflet.MovingMarker

* Request a Mapbox access token: [[https://www.mapbox.com/studio/account/tokens/]].

* Investigate further the "favicon" GET request in live version (GitHub).

* Investigate further the difference between =addTo()= and =openOn()= in Leaflet.

* +Leaflet GPX+ plugin alternatives?

- https://github.com/mapbox/leaflet-omnivore
- https://github.com/makinacorpus/Leaflet.FileLayer
- https://mercantour.info/gpxmap.html

* Exploit +Leaflet GPX+ plugin custom markers (start, end, waypoints, aso).

* Exploit +Leaflet GPX+ plugin functions (https://github.com/mpetazzoni/leaflet-gpx#available-functions).

* Google Maps API

For Google Maps API, registring a billing account is required, though 200$-worth calls are free ; possibility to configure daily limits to not exceed.

Ref: https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors

Alt: OpenStreetMap API?

Orientation to Leaflet

Best way seems to get global GPX of CRAW to display total routes and add another route for each participant from partial GPX data (with Leaflet GPX plugin: https://github.com/mpetazzoni/leaflet-gpx).

* In addition to the map, progress bars on the side?

* Better get inspired from [[https://www.atlassian.com/blog/statuspage/maintenance-page-examples]] (especially "Product Hunt" example with Midorino logo for instance).

* Further Links

https://en.wikipedia.org/wiki/Race_Across_the_World
https://runsignup.com/Race/CHH/AnywhereAnyPlace/CircumpolarRaceAroundtheWorld
https://www.facebook.com/groups/619915252295357/
https://fr.wikipedia.org/wiki/Nellie_Bly#Le_tour_du_monde_en_72_jours
https://fr.wikipedia.org/wiki/Le_Tour_du_monde_en_72_jours
https://blog.zombiesrungame.com/2020/09/25/nellie-bly-this-gal-someone-should-be-talking-about-her/
