#+TITLE:     GRAW - Logs
#+SUBTITLE:  Garmin Race Around the World - Logs
#+AUTHOR:    Midorino
#+EMAIL:     midorino@protonmail.com
#+DESCRIPTION: What may be done
#+LANGUAGE:  en

#+HTML_LINK_HOME: https://midorino.github.io

* TODO

** Investigate further on (semi)automatic data crawling from Garmin challenge ("BeautifulSoup"?).

** Request a Mapbox access token: [[https://www.mapbox.com/studio/account/tokens/]].

** Investigate further the "favicon" GET request in live version.

** Investigate further the difference between =addTo()= and =openOn()= in Leaflet.

** https://leafletjs.com/examples.html

** All remote resources (CSS, JS) in local versions?

** +Leaflet GPX+ plugin alternatives?

- https://github.com/mapbox/leaflet-omnivore
- https://github.com/makinacorpus/Leaflet.FileLayer

** Exploit +Leaflet GPX+ plugin custom markers (start, end, waypoints, aso).

** Exploit +Leaflet GPX+ plugin functions (https://github.com/mpetazzoni/leaflet-gpx#available-functions).

** Better get inspired from [[https://www.atlassian.com/blog/statuspage/maintenance-page-examples]] (especially "Product Hunt" example with Midorino logo for instance).

** Org-mode TODO syntax seems to not be well supported by GitHub previewier ; better to move "Roadmap" section to specific file (eg: "ROADMAP.org").

** Tools to get GPX

- *Google Maps x https://mapstogpx.com/*
- https://maps.openrouteservice.org

** Google Maps API

For Google Maps API, registring a billing account is required, though 200$-worth calls are free ; possibility to configure daily limits to not exceed.

Ref: https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors

Alt: OpenStreetMap API?

Orientation to Leaflet

Best way seems to get global GPX of CRAW to display total routes and add another route for each participant from partial GPX data (with Leaflet GPX plugin: https://github.com/mpetazzoni/leaflet-gpx).

** How to generate partial progress GPX data from calculate ratio of progress?

** In addition to the map, progress bars on the side?

** Virtual race progress via online map

https://www.e-monsite.com/pages/tutoriels/configuration-avancee-du-site/obtenir-une-cle-google-maps-api.html

https://console.developers.google.com/apis/

https://snazzymaps.com/download-example/1

https://developers.google.com/maps/documentation/javascript/shapes#maps_polyline_simple-javascript

For CRAW map: https://www.craw.racing/results/

** Further Links

https://en.wikipedia.org/wiki/Race_Across_the_World
https://runsignup.com/Race/CHH/AnywhereAnyPlace/CircumpolarRaceAroundtheWorld
https://www.facebook.com/groups/619915252295357/
https://fr.wikipedia.org/wiki/Nellie_Bly#Le_tour_du_monde_en_72_jours
https://fr.wikipedia.org/wiki/Le_Tour_du_monde_en_72_jours
https://blog.zombiesrungame.com/2020/09/25/nellie-bly-this-gal-someone-should-be-talking-about-her/
