#+TITLE:     GRAW - Log - 2020-12-11
#+SUBTITLE:  Garmin Race Around the World - Log - 2020-12-11
#+AUTHOR:    Midorino
#+EMAIL:     midorino@protonmail.com
#+DESCRIPTION: What has been done
#+LANGUAGE:  en

#+HTML_LINK_HOME: https://midorino.github.io

* 2020-12-11
CLOSED: [2020-12-11]
:PROPERTIES:
:CREATED:  [2020-12-11]
:END:

** [FEAT-AAL] Street View

*** SOTA

**** Google Street View

Initial consideration as most common tool.

But API key required and possibly non free (TBC).

Furthermore, use of URL schemes construction without previous requirements against Google's terms of service.

References:

- https://developers.google.com/maps/documentation/javascript/streetview
- https://gis.stackexchange.com/questions/86774/what-do-the-parameters-for-google-streetview-mean
- https://stackoverflow.com/questions/387942/google-street-view-url
- https://gis.stackexchange.com/questions/70636/incorporate-google-streetview-into-a-leaflet-map

**** MapillaryJS

Best alternative candidate: [[https://www.mapillary.com/mapillaryjs][MapillaryJS]].

Not as much world map covered though.

**** Other candidates

- http://openstreetcam.org
- https://yandex.com/maps

*** Development

Developer account created on [[https://www.mapillary.com]].

Application with default parameters registered.

Following [[https://mapillary.github.io/mapillary-js/][MapillaryJS Documentation]]:

- [X] Add Mapillary CDN resources
- [X] Add MapillaryJS viewer
- [ ] Add MapillaryJS x Leaflet integration
- [ ] Update Mapillary resources to local

**** Leaflet integration

Reference: [[MapillaryJS + Leaflet][https://bl.ocks.org/oscarlorentzon/0a11029a5627028c445a38016c76fb3a]].

But previous reference must be adapted - here, an update on the MapillaryJS viewer fires an update on the Leaflet map.

Desired case is somewhat simple: for each participant current marker, add an option to open a MapillaryJS viewer on its coordinates.